frameworkVersion: "=1.24.1"
service: UserService
provider:
  name: aws
  runtime: nodejs6.10
  profile: default
  region: us-east-1
  memorySize: 256
  timeout: 10
  environment:
    MONGO_URI: ${file(../secrets.${opt:stage, self:provider.stage}.yml):MONGO_URI}
plugins:
  - serverless-domain-manager
  - serverless-secrets-plugin
package: 
  individually: true
  exclude:
    - ./**
custom:
  stage: ${opt:stage, self:provider.stage}
  domains:
    prod: api.yourwebsite.com
    staging: staging.api.yourwebsite.com
    dev: dev.api.yourwebsite.com
  customDomain:
    basePath: "user"
    domainName: ${self:custom.domains.${self:custom.stage}}
    stage: "${self:custom.stage}"
    createRoute53Record: true
  secretsFilePathPrefix: ../
functions:
  login:
    handler: Login/index.handler
    description: Function to login by user, provide token for further method calling
    events:
      - http:
          path: /login
          method: post
          private: false
    package:
      include: 
        - Login/**
  authorizer:
      handler: Authorizer/index.handler
      description: Common authorizer function that authenticate user's token for all routes
      package:
        include: 
          - Authorizer/**